
server:
  servlet:
    context-path: /free
  port: 2023
  connection-timeout: 5000
  compression:
    enabled: true
    min-response-size: 1
  tomcat:
    max-connections: 1000
    max-threads: 1000
    min-spare-threads: 500
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  datasource:
    free:
      type: com.alibaba.druid.pool.DruidDataSource
      source:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.105.105.90:3306/lottery?characterEncoding=utf8&useSSL=false
        username: root
        password: 0c73f6b6fa
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 20
        maxActive: 200
        # 配置获取连接等待超时的时间(毫秒)
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
        filters: stat, wall
        # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
redis:
  database: 5
  host: 39.98.190.70
  port: 6379
  password: 0c73f6b6fa
  timeout: 1000
  pool:
    maxActive: 20
    maxWait: 1000
    maxIdle: 30
    minIdle: 0

logging:
  level:
    com.iotep.free.mapper: DEBUG